config/routes.rb
Rails.application.routes.draw do
 devise_for :users
 resources :products
 #resources  :checkouts
 root 'products#index'
  post "checkouts/create", to: "checkouts#create"
 resources :webhooks, only: [:create]
 get "success", to: "checkouts#success"
 get "cancel", to: "checkouts#cancel"

 post "products/add_to_cart/:id", to: "products#add_to_cart", as: "add_to_cart"
 delete "products/remove_from_cart/:id", to: "products#remove_from_cart", as: "remove_from_cart"
 #root 'homes#index'
 # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
 monetize :price, as: :price_cents


def to_s
   name
 end

 # transform shopping cart products into an array of line items

 def to_builder
  #debugger
   Jbuilder.new do |product|
     product.price stripe_price_id
     product.quantity 1
   end
 end

 after_create do
 	debugger
   product = Stripe::Product.create(name: name)
   price = Stripe::Price.create(product: product, unit_amount: self.price, currency: "usd")
   update(stripe_product_id: product.id, stripe_price_id: price.id )
 end
end

app/models/user.rb
class User < ApplicationRecord
	# Include default devise modules. Others available are:
 # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
 devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

 def to_s
   email
 end

 after_create do
 	debugger
   customer = Stripe::Customer.create(email: email)
   update(customer_id: customer.id)
 end
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
   before_action :configure_permitted_parameters, if: :devise_controller?
   before_action :initialize_session
   before_action :load_cart
   
protected

    def configure_permitted_parameters
       devise_parameter_sanitizer.permit(:sign_up, keys: [:stripe_customer_id])
    end
   

 private
 def initialize_session
   session[:cart] ||= [] # empty cart = empty array
 end
 def load_cart
   # @cart = Product.find(session[:cart])
   # Product.all.pluck(:id) => 1, 2
   # Product.find(1, 2, 3) => error
   # Product.where(id: [1, 2, 3]) => 1, 2
   @cart = Product.where(id: session[:cart])
 end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
      before_action :authenticate_user!
        skip_before_action :verify_authenticity_token

        def new
            if params[:product_id].present?
               @product = Product.find(params[:product_id])
            end
        end
       
       def create
           @product = Product.find(params[:product_id])
           token = Stripe::Token.create( :card =>{ :number => params[:number],             :exp_month => params[:month], :exp_year => params[:year], :cvc =>             params[:cvc] }, )
           @user = current_user
           unless @user.customer_id.present?
               customer = Stripe::Customer.create(
                    email: @user.email,source: token.id)
               @user.update_attribute("customer_id", customer.id)
           end
          customer = Stripe::Customer.all.retrieve(@user.customer_id)
          begin  
               charge = Stripe::Charge.create(
               customer: current_user.customer_id,
               amount:   @product.price_in_cents,
               currency: 'usd'
           )
               flash[:notice] = 'Card charged successfully.'
         rescue Stripe::CardError => e
               flash[:notice] = 'That card is presently on fire!'
         rescue => e
               flash[:notice] = 'Some error occurred.'
         end
         redirect_to root_path
         rescue Stripe::CardError => e
            flash[:error] = e.message
            redirect_to @product
         end
end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
	

	def create
		debugger
    if @cart.pluck(:currency).uniq.length > 1
      redirect_to products_path, alert: "You can not select products with different currencies in one checkout"
    else
    	#debugger
      @session = Stripe::Checkout::Session.create({
        customer: current_user.customer_id,
        payment_method_types: ['card'],
        line_items: @cart.collect { |item| item.to_builder.attributes! },
        allow_promotion_codes: true,
        mode: 'payment',
        success_url: success_url + "?session_id={CHECKOUT_SESSION_ID}",
        cancel_url: cancel_url
      }) 
    end
      respond_to do |format|
         format.js
         format.html
       end

     
  end


  def success
    if params[:session_id].present? 
      # session.delete(:cart)
      session[:cart] = [] # empty cart = empty array
      @session_with_expand = Stripe::Checkout::Session.retrieve({ id: params[:session_id], expand: ["line_items"]})
      @session_with_expand.line_items.data.each do |line_item|
        product = Product.find_by(stripe_product_id: line_item.price.product)
      end
    else
      redirect_to cancel_url, alert: "No info to display"
    end 
  end

  def cancel
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :set_product, only: %i[ show update destroy ]

 def add_to_cart
   #debugger
   id = params[:id].to_i
   session[:cart] << id unless session[:cart].include?(id)
   redirect_to products_path
 end

 def remove_from_cart
   id = params[:id].to_i
   session[:cart].delete(id)
   redirect_to products_path
 end

 def index
   @products = Product.all
 end

 def show
 end

 def new
   @product = Product.new
 end

 def create
   @product = Product.new(product_params)
   if @product.save
     redirect_to @product, notice: "Product was successfully created."
   else
     render :new, status: :unprocessable_entity
   end
 end

 def update
   if @product.update(product_params)
     redirect_to @product, notice: "Product was successfully updated."
   else
     render :edit, status: :unprocessable_entity
   end
 end

 def destroy
   @product.destroy
   redirect_to products_url, notice: "Product was successfully destroyed."
 end

 private
   def set_product
     @product = Product.find(params[:id])
   end

   def product_params
     params.require(:product).permit(:name, :price, :price_cents, :currency, :user_id)
   end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/charges/new.html.erb
<%= javascript_include_tag "https://js.stripe.com/v2/" %>
        <%= form_for current_user.credit_cards.new, url: charges_path do |f| %>
            <%= hidden_field_tag :product_id, @product.id %>
          <ul class="form-list">
            <li class="form-list__row">
              <label>Card Number</label>
              <div id="input--cc" class="creditcard-icon">
                <input type="text" name="number" required="" maxlength="16" />
              </div>
            </li>
            <li class="form-list__row form-list__row--inline">
              <div>
                <label>Expiration Date</label>
                <div class="form-list__input-inline">
                  <input type="text" name="month" placeholder="MM"                                      minlength="2" maxlength="2" required="" max="12" />
                  <input type="text" name="year" placeholder="YY"                                          maxlength="4" required="" />
                </div>
              </div>
              <div>
                  <label>
                     CVC
                  </label>
                  <input type="text" name="cvc" placeholder="123"                                            maxlength="3" required="" />
              </div>
            </li>
            <li>
              <button type="submit" class="button">Pay Now</button>
            </li>
         </ul>
<%end%>

app/views/checkouts/create.html.erb
<script type="text/javascript">
	var stripe = Stripe("<%= Rails.configuration.stripe[:publishable_key] %>");
stripe.redirectToCheckout({
  sessionId: '<%= @session.id %>'
}).then(function (result) {
  console.log(result.error.message);
});
</script>

app/views/checkouts/create.js.erb
var stripe = Stripe("<%= Rails.configuration.stripe[:publishable_key] %>");
stripe.redirectToCheckout({
  sessionId: '<%= @session.id %>'
}).then(function (result) {
  console.log(result.error.message);
});

app/views/checkouts/success.html.erb
<h1>Success</h1> 
Checkout status: <%= @session_with_expand.payment_status %> <br>
Amount paid: <%= @session_with_expand.amount_total/100.to_f %> 
<%= @session_with_expand.currency %> 
<% @session_with_expand.line_items.data.each do |line_item| %>
<% product = Product.find_by(stripe_product_id: line_item.price.product) %> <br>
<%= product.name %> 
<% end %>
<br><%=link_to "home",root_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <head> 
    <title>
      Stripe
    </title> 
  <meta name="viewport" content="width=device-width,initial-scale=1">
   <%= csrf_meta_tags %>
    <%= csp_meta_tag %> 
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js">
        </script>
         <script src="https://js.stripe.com/v3/">
           
         </script>
            <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %> <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head >
           
           <% if notice %>
            <p class="alert alert-success">
              <%= notice %>
            </p> 
              
              <% end %> 
              
              <% if alert %>
               <p class="alert alert-danger">
                <%= alert %>
                  
                </p> <% end %> 
          <p class="navbar-text float-right">
           <% if user_signed_in? %> Logged in as <strong><%= current_user.email %></strong>. <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> | <%= button_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %> 
           <h1>Shopping cart</h1>
            <% @cart.each do |product| %>
             <%= product.name %>
              <br> <% end %> 
              <% if @cart.present? %>
               <%= @cart.collect { |item| item.to_builder.attributes! } %>
               <%#debugger%>
                <%= button_to "Buy now!", checkouts_create_path(id: @cart.ids.first), data: { disable_with: "validating..."} %>
                 <% end %> <hr> 
                 <% else %>
                  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %> | <%= link_to "Login", new_user_session_path, :class => 'navbar-link' %> 
                  <% end %> </p> 
    <body> 
      <%= yield %> 
  </body>
</html>

app/views/products/index.html.erb
<h1>Hello, Rails!</h1>
<h1>Products</h1>
 <table> 
 	<thead> 
 		<tr> <th>Name</th> 
	<th>Currency</th>
	 <th>Price</th>
	  <th>Stripe Product Id</th>
	   <th>Stripe Price Id</th>
	    <th>Stripe Currency</th>
	     <th>Stripe Price</th> 
	     <th>Shopping cart</th>
	      <th>Sales count</th> 
	      <th colspan="2"></th>
	       </tr>
	        </thead>
	         <tbody> <% @products.each do |product| %> <tr>
	          <td><%= product.name %></td>
	           <td><%= product.currency %></td> 
	           <td><%= product.price_cents %></td>
	            <td><%= product.stripe_product_id %></td>
	             <td><%= product.stripe_price_id %></td>
	              <td><%= Stripe::Price.retrieve(product.stripe_price_id)&.currency %></td> 
                   <td><%= Stripe::Price.retrieve(product.stripe_price_id)&.unit_amount/100 %> </td>
	               <td> <%if @cart.include?(product) %>
	                <%= button_to "Remove from cart", remove_from_cart_path(product), method: :delete %> 
	                <%else %> <%= button_to "Add to cart", add_to_cart_path(product) %> 
	                <%end %> 
	            </td> <td><%#= product.sales_count %></td>
	             <td><%= link_to 'Show', product %></td>
	              <td><%= button_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td> </tr> 
	              <% end %> 
            </tbody>
</table> <br> <%= link_to 'New Product', new_product_path %> <hr>

app/views/products/new.html.erb
<%= form_with(model: @product) do |form| %>
 <% if @product.errors.any? %>
   <div id="error_explanation">
     <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

     <ul>
       <% @product.errors.each do |error| %>
         <li><%= error.full_message %></li>
       <% end %>
     </ul>
   </div>
 <% end %>

 <div class="field">
   <%= form.label :name %>
   <%= form.text_field :name %>
 </div>

<div class="field">
   <%= form.label :user_id %>
   <%= form.text_field :user_id,value: current_user.id%>
 </div>

 <div class="field">
   <%= form.label :currency %>
   <%= form.select :currency, ["usd", "eur", "pln", "uah"] %>
 </div>

 <div class="field">
   <%= form.label :price %>
   <%= form.text_field :price_cents %>
 </div>

 <div class="actions">
   <%= form.submit %>
 </div>
<% end %>

app/views/products/show.html.erb
<p>
 <strong>Name:</strong>
 <%= @product.name %>
</p>

<p>
 <strong>Price:</strong>
 <%= @product.price_cents %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>